TRUNCATE TABLE [HRS-Global$Agency Contract]
GO
INSERT INTO [dbo].[HRS-Global$Agency Contract]
           ([Code]
           ,[Type]
           ,[Description]
           ,[Model]
           ,[Value %]
           ,[Value Total (LCY)]
           ,[Contract Calc_ Func_ Code]
           ,[Valid from]
           ,[Locked]
           ,[User ID]
           ,[No_ Series]
           ,[Inserted by User]
           ,[Inserted at]
           ,[Modified by User]
           ,[Modified at]
           ,[Currency Code]
           ,[Limit]
           ,[Deviating Cost Unit 1]
           ,[Deviating Cost Unit 2]
           ,[Included Value for Cost Unit 2])
SELECT [Code]
      ,[Type]
      ,[Description]
      ,[Model]
      ,[Value %]
      ,[Value Total (LCY)]
      ,[Contract Calc_ Func_ Code]
      ,[Valid from]
      ,[Locked]
      ,[User ID]
      ,[No_ Series]
      ,[Inserted by User]
      ,[Inserted at]
      ,[Modified by User]
      ,[Modified at]
      ,[Currency Code]
      ,[Limit]
      ,[Deviating Cost Unit 1]
      ,[Deviating Cost Unit 2]
      ,[Included Value for Cost Unit 2]
  FROM [dbo].[HRS$Agency Contract]
GO


