TRUNCATE TABLE [HRS-Global$Booking Source]
GO
INSERT INTO [dbo].[HRS-Global$Booking Source]
           ([No_]
           ,[Name]
           ,[Category]
           ,[Affiliate Partner No_]
           ,[Client Comment]
           ,[Client Contact Name]
           ,[Client Contact Phone]
           ,[Client Contact E-Mail]
           ,[Client Type]
           ,[State]
           ,[Interface]
           ,[Corrections Blocked]
           ,[Is GDS]
           ,[Source Class]
           ,[Source Mapping])
SELECT [No_]
      ,[Name]
      ,[Category]
      ,[Affiliate Partner No_]
      ,[Client Comment]
      ,[Client Contact Name]
      ,[Client Contact Phone]
      ,[Client Contact E-Mail]
      ,[Client Type]
      ,[State]
      ,[Interface]
      ,[Corrections Blocked]
      ,[Is GDS]
      ,[Source Class]
      ,[Source Mapping]
  FROM [dbo].[HRS$Booking Source]
GO

