TRUNCATE TABLE [HRS-Global$Contact]
GO
INSERT INTO [dbo].[HRS-Global$Contact]
           ([No_]
           ,[Name]
           ,[Search Name]
           ,[Name 2]
           ,[Address]
           ,[Address 2]
           ,[City]
           ,[Phone No_]
           ,[Telex No_]
           ,[Territory Code]
           ,[Currency Code]
           ,[Language Code]
           ,[Salesperson Code]
           ,[Country_Region Code]
           ,[Last Date Modified]
           ,[Fax No_]
           ,[Telex Answer Back]
           ,[VAT Registration No_]
           ,[Picture]
           ,[Post Code]
           ,[County]
           ,[E-Mail]
           ,[Home Page]
           ,[No_ Series]
           ,[Type]
           ,[Company No_]
           ,[Company Name]
           ,[Lookup Contact No_]
           ,[First Name]
           ,[Middle Name]
           ,[Surname]
           ,[Job Title]
           ,[Initials]
           ,[Extension No_]
           ,[Mobile Phone No_]
           ,[Pager]
           ,[Organizational Level Code]
           ,[Exclude from Segment]
           ,[External ID]
           ,[Correspondence Type]
           ,[Salutation Code]
           ,[Search E-Mail]
           ,[Last Time Modified]
           ,[E-Mail 2]
           ,[Chain]
           ,[Brand]
           ,[Contract Status]
           ,[Timestamp DB2]
           ,[Hotel Status]
           ,[Modified by User]
           ,[Tax Area Code]
           ,[Special Agreement]
           ,[Special Agreement Fix]
           ,[Special Agreement Percent]
           ,[Special Agreement Function]
           ,[Special Agreement Valid From]
           ,[Blocked for further postings]
           ,[Hotel Reference Avail Priority]
           ,[Hotel Reference Code]
           ,[Hotel Reference MuseID]
           ,[Hotel Reference CTS]
           ,[COS Valid from]
           ,[COS First Name]
           ,[COS Last Name]
           ,[COS Position]
           ,[COS Status]
           ,[COS Document ID]
           ,[COS CTS]
           ,[Testhotel]
           ,[GTC Status]
           ,[GTC 2024 CTS])
SELECT [No_]
      ,[Name]
      ,[Search Name]
      ,[Name 2]
      ,[Address]
      ,[Address 2]
      ,[City]
      ,[Phone No_]
      ,[Telex No_]
      ,[Territory Code]
      ,[Currency Code]
      ,[Language Code]
      ,[Salesperson Code]
      ,[Country_Region Code]
      ,[Last Date Modified]
      ,[Fax No_]
      ,[Telex Answer Back]
      ,[VAT Registration No_]
      ,[Picture]
      ,[Post Code]
      ,[County]
      ,[E-Mail]
      ,[Home Page]
      ,[No_ Series]
      ,[Type]
      ,[Company No_]
      ,[Company Name]
      ,[Lookup Contact No_]
      ,[First Name]
      ,[Middle Name]
      ,[Surname]
      ,[Job Title]
      ,[Initials]
      ,[Extension No_]
      ,[Mobile Phone No_]
      ,[Pager]
      ,[Organizational Level Code]
      ,[Exclude from Segment]
      ,[External ID]
      ,[Correspondence Type]
      ,[Salutation Code]
      ,[Search E-Mail]
      ,[Last Time Modified]
      ,[E-Mail 2]
      ,[Chain]
      ,[Brand]
      ,[Contract Status]
      ,[Timestamp DB2]
      ,[Hotel Status]
      ,[Modified by User]
      ,[Tax Area Code]
      ,[Special Agreement]
      ,[Special Agreement Fix]
      ,[Special Agreement Percent]
      ,[Special Agreement Function]
      ,[Special Agreement Valid From]
      ,[Blocked for further postings]
      ,[Hotel Reference Avail Priority]
      ,[Hotel Reference Code]
      ,[Hotel Reference MuseID]
      ,[Hotel Reference CTS]
      ,[COS Valid from]
      ,[COS First Name]
      ,[COS Last Name]
      ,[COS Position]
      ,[COS Status]
      ,[COS Document ID]
      ,[COS CTS]
      ,[Testhotel]
      ,[GTC Status]
      ,[GTC 2024 CTS]
  FROM [dbo].[HRS$Contact]
GO


