TRUNCATE TABLE [HRS-Global$Country_Region]
GO
INSERT INTO [dbo].[HRS-Global$Country_Region]
           ([Code]
           ,[Name]
           ,[EU Country_Region Code]
           ,[Intrastat Code]
           ,[Address Format]
           ,[Contact Address Format]
           ,[Global Dimension 2 Code]
           ,[Customer Template Code]
           ,[ISO Code]
           ,[Culture Info]
           ,[Signature]
           ,[Bank Country Code]
           ,[EU Standard]
           ,[Continent]
           ,[Responsibility Center]
           ,[Income Cost Carrier Code]
           ,[Primary Language Code]
           ,[EU affiliation]
           ,[max_ IBAN Length]
           ,[Length of Bank Branch Code]
           ,[Invoicing in local currency]
           ,[Currency Code]
           ,[Default Length Branch Code]
           ,[Default Length Account No_]
           ,[ISO Bank Code]
           ,[Accounting Period]
           ,[VAT Registration Obligation]
           ,[Vend_ Gen_ Bus_ Posting Group]
           ,[Cust_ Gen_ Bus_ Posting Group]
           ,[Commission Value Limit (LCY)]
           ,[Reminder Termscode]
           ,[Cost Center Code Sourcing_MP]
           ,[TOMS]
           ,[TOMS Start Date]
           ,[Payment Inf_ Country Code]
           ,[Windows Language ID]
           ,[Area Format]
           ,[Alternate Area Format]
           ,[Area Format Explanation]
           ,[Postal Code Length]
           ,[Check rule for Postal Code]
           ,[Postal Code Required]
           ,[Accounting Period Text]
           ,[Tax Number Category]
           ,[VAT ID Pattern])
SELECT [Code]
      ,[Name]
      ,[EU Country_Region Code]
      ,[Intrastat Code]
      ,[Address Format]
      ,[Contact Address Format]
      ,[Global Dimension 2 Code]
      ,[Customer Template Code]
      ,[ISO Code]
      ,[Culture Info]
      ,[Signature]
      ,[Bank Country Code]
      ,[EU Standard]
      ,[Continent]
      ,[Responsibility Center]
      ,[Income Cost Carrier Code]
      ,[Primary Language Code]
      ,[EU affiliation]
      ,[max_ IBAN Length]
      ,[Length of Bank Branch Code]
      ,[Invoicing in local currency]
      ,[Currency Code]
      ,[Default Length Branch Code]
      ,[Default Length Account No_]
      ,[ISO Bank Code]
      ,[Accounting Period]
      ,[VAT Registration Obligation]
      ,[Vend_ Gen_ Bus_ Posting Group]
      ,[Cust_ Gen_ Bus_ Posting Group]
      ,[Commission Value Limit (LCY)]
      ,[Reminder Termscode]
      ,[Cost Center Code Sourcing_MP]
      ,[TOMS]
      ,[TOMS Start Date]
      ,[Payment Inf_ Country Code]
      ,[Windows Language ID]
      ,[Area Format]
      ,[Alternate Area Format]
      ,[Area Format Explanation]
      ,[Postal Code Length]
      ,[Check rule for Postal Code]
      ,[Postal Code Required]
      ,[Accounting Period Text]
      ,[Tax Number Category]
      ,[VAT ID Pattern]
  FROM [dbo].[HRS$Country_Region]
GO


